version: '3.1'
services:
  database-exame-front-cge:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./bd:/data/db

  back-end-api:
    build:
      context: ./back
      dockerfile: DockerFile
    expose:
      - 1234
    ports:
      - 1234:1234

  front-end:
    build:
      context: ./front
      dockerfile: DockerFile
    expose:
      - 8080
    ports:
      - 8080:8080
